apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm-container
        image: ghcr.io/berriai/litellm:main-latest
        imagePullPolicy: Always
        env:
        - name: LITELLM_MASTER_KEY
          value: "sk-XXXXXXXXXXXX"
        - name: DATABASE_URL
          value: 'postgresql://postgres:testpassword@postgresql-db:5432/postgres'
        args:
        - "--config"
        - "/app/litellm-config.yaml" # Update the path to mount the config file
        volumeMounts: # Define volume mount for proxy_config.yaml
        - name: config-volume
          mountPath: /app
          readOnly: true
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveliness
          #     port: 4000
          #   initialDelaySeconds: 120
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /health/readiness
          #     port: 4000
          #   initialDelaySeconds: 120
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3
          #   timeoutSeconds: 10
      volumes: # Define volume to mount proxy_config.yaml
      - name: config-volume
        configMap:
          name: litellm-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
spec:
  selector:
    app: litellm
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  # type: LoadBalancer
