
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-llama3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3-server
  template:
    metadata:
      labels:
        app: llama3-server
    spec:
      containers:
      - name: inference-server
        image: ghcr.io/huggingface/text-generation-inference:2.2.0
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        args: #https://huggingface.co/docs/text-generation-inference/en/basic_tutorials/launcher
        - --model-id=$(MODEL_ID)
        - --num-shard=1
        - --trust-remote-code
        - --max-total-tokens=8192
        env:
        - name: MODEL_ID
          value: meta-llama/Meta-Llama-3.1-8B-Instruct
        - name: FLASH_DECODING
          value: "1"
        - name: PORT
          value: "8000"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token

---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  selector:
    app: llama3-server
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
